name: Answer

on:
  push:
    branches: [ "*" ]
    paths:
      - 'Answer/**'          # Only run if files in Answer folder change
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore BaseWebApplication/BaseWebApplication.sln
    - name: Build
      run: dotnet build --no-restore BaseWebApplication/BaseWebApplication.sln
    - name: Test Answer.Domain.Tests
      run: dotnet test --no-build --verbosity normal Answer/tests/Answer.Domain.Tests/Answer.Domain.Tests.csproj
    - name: Test Answer.Infrastructure.Tests
      run: dotnet test --no-build --verbosity normal Answer/tests/Answer.Infrastructure.Tests/Answer.Infrastructure.Tests.csproj
    - name: Test Answer.Api.IntegrationTests
      run: dotnet test --no-build --verbosity normal Answer/tests/Answer.Api.IntegrationTests/Answer.Api.IntegrationTests.csproj
